# Generated by Django 2.0.7 on 2018-07-30 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_categories',
            fields=[
                ('category', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('size', models.CharField(choices=[('SM', 'small'), ('LG', 'large'), ('NA', 'one size')], max_length=16)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Menu_categories')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_num', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order_line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_num', models.IntegerField()),
                ('size', models.CharField(blank=True, choices=[('SM', 'small'), ('LG', 'large'), ('NA', 'one size')], max_length=16, null=True)),
                ('toppings', models.CharField(blank=True, choices=[('CHEESE', 'cheese'), ('1', '1 topping'), ('2', '2 toppings'), ('3', '3 toppings'), ('SPECIAL', 'special'), ('NA', 'no toppings')], max_length=64, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Menu_categories')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Menu_items')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza_toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=64)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('size', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_addons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_on', models.CharField(max_length=64)),
                ('available', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Sizes')),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('option', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='order_line',
            name='sub_addons',
            field=models.ManyToManyField(blank=True, to='orders.Sub_addons'),
        ),
        migrations.AddField(
            model_name='order_line',
            name='topping_items',
            field=models.ManyToManyField(blank=True, to='orders.Pizza_toppings'),
        ),
        migrations.AddField(
            model_name='order',
            name='lines',
            field=models.ManyToManyField(to='orders.Order_line'),
        ),
    ]
