# Generated by Django 2.0.7 on 2018-07-30 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_addons',
            name='available',
        ),
        migrations.RemoveField(
            model_name='sub_addons',
            name='price',
        ),
    ]
