# Generated by Django 2.0.7 on 2018-07-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180730_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_addons',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
