# Generated by Django 2.0.7 on 2018-07-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180725_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_categories',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
