# Generated by Django 2.0.7 on 2018-07-30 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_sub_addons_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Menu_categories'),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Sizes'),
        ),
    ]
