# Generated by Django 2.0.7 on 2018-07-30 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180730_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='toppings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Toppings'),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Sizes'),
        ),
    ]
