# Generated by Django 2.0.7 on 2018-07-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_menu_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_items',
            name='price',
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='toppings',
            field=models.CharField(choices=[('CHEESE', 'cheese'), (1, '1 topping'), (2, '2 toppings'), (3, '3 toppings'), ('SPECIAL', 'special')], max_length=64),
        ),
    ]
