# Generated by Django 2.0.7 on 2018-07-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180725_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
