# Generated by Django 2.0.7 on 2018-07-30 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180730_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_items',
            name='toppings',
        ),
    ]
