# Generated by Django 2.0.7 on 2018-07-30 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_menu_items_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_items',
            name='size',
        ),
    ]
