# Generated by Django 2.0.7 on 2018-07-30 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_menu_items_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Sizes'),
        ),
    ]
