# Generated by Django 2.0.7 on 2018-07-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180725_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_items',
            name='price',
        ),
    ]
