# Generated by Django 2.0.7 on 2018-07-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_menu_items_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='addons',
            field=models.ManyToManyField(blank=True, to='orders.Sub_addons'),
        ),
    ]
