# Generated by Django 2.0.7 on 2018-07-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_menu_items_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
