# Generated by Django 2.0.7 on 2018-07-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_menu_items_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
