# Generated by Django 2.0.7 on 2018-07-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_menu_items_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_items',
            name='category',
        ),
        migrations.DeleteModel(
            name='Menu_items',
        ),
    ]
