# Generated by Django 2.0.7 on 2018-07-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20180725_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('available', models.BooleanField(default=True)),
                ('size', models.CharField(choices=[('SM', 'small'), ('LG', 'large')], max_length=16)),
                ('toppings', models.CharField(choices=[('CHEESE', 'cheese'), ('1', '1 topping'), ('2', '2 toppings'), ('3', '3 toppings'), ('SPECIAL', 'special')], max_length=64)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('category', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='orders.Menu_categories')),
            ],
        ),
    ]
