# Generated by Django 2.0.7 on 2018-07-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20180731_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_line',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order_line',
            name='size',
        ),
        migrations.RemoveField(
            model_name='order_line',
            name='toppings',
        ),
    ]
