# Generated by Django 2.0.7 on 2018-07-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20180725_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_addons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on', models.CharField(max_length=64)),
                ('size', models.CharField(choices=[('SM', 'small'), ('LG', 'large')], max_length=16)),
                ('available', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('restricted_menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='orders.Menu_items')),
            ],
        ),
    ]
