# Generated by Django 2.0.7 on 2018-07-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20180731_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lines',
            field=models.ManyToManyField(blank=True, to='orders.Order_line'),
        ),
    ]
