# Generated by Django 2.0.7 on 2018-07-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20180725_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_items',
            name='category',
        ),
        migrations.DeleteModel(
            name='Menu_items',
        ),
    ]
