# Generated by Django 2.0.7 on 2018-07-31 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20180731_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='lines',
        ),
        migrations.AddField(
            model_name='order_line',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.Order'),
        ),
    ]
