# Generated by Django 2.0.7 on 2018-07-31 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20180731_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_addons',
            old_name='add_on',
            new_name='addon',
        ),
    ]
