# Generated by Django 2.0.7 on 2018-07-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20180731_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
            ],
        ),
    ]
