# Generated by Django 2.0.7 on 2018-07-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20180726_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_line',
            old_name='menu_item',
            new_name='item',
        ),
    ]
