# Generated by Django 2.0.7 on 2018-08-01 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20180801_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default='placed', on_delete=django.db.models.deletion.CASCADE, to='orders.Order_status'),
        ),
    ]
